import type { Collection, Product, Testimonial } from "@/types";

export const products: Product[] = [
  {
    id: "vestido-corset-rubi",
    name: "Vestido Corset Rubi",
    category: "Ocasião Especial",
    price: 2750,
    image: "/images/products/vestido-corset-rubi.jpg",
    imageBack: "/images/products/vestido-corset-rubi-costas.jpg",
    badge: "Mais Vendido",
    bestSeller: true,
  },
  {
    id: "vestido-longo-dourado",
    name: "Vestido Longo Dourado",
    category: "Vestidos",
    price: 3450,
    image: "/images/products/vestido-longo-dourado.jpg",
    imageBack: "/images/products/vestido-longo-dourado-costas.jpg",
    badge: "Mais Vendido",
    bestSeller: true,
  },
  {
    id: "conjunto-suede-preto",
    name: "Conjunto Suede Preto",
    category: "Conjuntos",
    price: 1850,
    oldPrice: 2150,
    image: "/images/products/conjunto-suede-preto.jpg",
    imageBack: "/images/products/conjunto-suede-preto-costas.jpg",
    badge: "Mais Vendido",
    bestSeller: true,
  },
  {
    id: "vestido-veludo-esmeralda",
    name: "Vestido Veludo Esmeralda",
    category: "Ocasião Especial",
    price: 2950,
    image: "/images/products/vestido-veludo-esmeralda.jpg",
    badge: "Mais Vendido",
    bestSeller: true,
  },
  {
    id: "vestido-corset-perola",
    name: "Vestido Corset Pérola",
    category: "Ocasião Especial",
    price: 2750,
    image: "/images/products/vestido-corset-perola.jpg",
    imageBack: "/images/products/vestido-corset-perola-costas.jpg",
    badge: "Novo",
  },
  {
    id: "vestido-longo-sunset",
    name: "Vestido Longo Sunset",
    category: "Vestidos",
    price: 3450,
    oldPrice: 3900,
    image: "/images/products/vestido-longo-sunset.jpg",
    imageBack: "/images/products/vestido-longo-sunset-costas.jpg",
    badge: "Promoção",
  },
  {
    id: "vestido-longo-azul",
    name: "Vestido Longo Azul Oceano",
    category: "Vestidos",
    price: 3450,
    image: "/images/products/vestido-longo-azul.jpg",
    badge: "Novo",
  },
  {
    id: "conjunto-suede-verde",
    name: "Conjunto Suede Verde-Sálvia",
    category: "Conjuntos",
    price: 1850,
    image: "/images/products/conjunto-suede-verde.jpg",
    imageBack: "/images/products/conjunto-suede-verde-costas.jpg",
    badge: "Novo",
  },
  {
    id: "conjunto-suede-bege",
    name: "Conjunto Suede Bege",
    category: "Conjuntos",
    price: 1850,
    image: "/images/products/conjunto-suede-bege.jpg",
    imageBack: "/images/products/conjunto-suede-bege-costas.jpg",
    badge: "Novo",
  },
  {
    id: "bermuda-canelada-bordo",
    name: "Bermuda Canelada Bordô",
    category: "Bermudas",
    price: 950,
    image: "/images/products/bermuda-canelada-bordo.jpg",
    imageBack: "/images/products/bermuda-canelada-bordo-costas.jpg",
    badge: "Novo",
  },
  {
    id: "bermuda-canelada-azul",
    name: "Bermuda Canelada Azul-Marinho",
    category: "Bermudas",
    price: 950,
    image: "/images/products/bermuda-canelada-azul.jpg",
    imageBack: "/images/products/bermuda-canelada-azul-costas.jpg",
    badge: "Novo",
  },
  {
    id: "bermuda-canelada-camel",
    name: "Bermuda Canelada Camel",
    category: "Bermudas",
    price: 950,
    image: "/images/products/bermuda-canelada-camel.jpg",
    badge: "Novo",
  },
  {
    id: "calcoes-comfy-rosa",
    name: "Calções Comfy Rosa",
    category: "Calções",
    price: 650,
    image: "/images/products/calcoes-comfy-rosa.jpg",
    imageBack: "/images/products/calcoes-comfy-rosa-costas.jpg",
    badge: "Novo",
  },
  {
    id: "calcoes-comfy-cinza",
    name: "Calções Comfy Cinza",
    category: "Calções",
    price: 650,
    oldPrice: 780,
    image: "/images/products/calcoes-comfy-cinza.jpg",
    imageBack: "/images/products/calcoes-comfy-cinza-costas.jpg",
    badge: "Promoção",
  },
  {
    id: "duo-calcoes-preto-branco",
    name: "Duo Calções Preto & Branco",
    category: "Calções",
    price: 1150,
    oldPrice: 1300,
    image: "/images/products/duo-calcoes-preto-branco.jpg",
    badge: "Promoção",
  },
  {
    id: "calca-plissada-camel",
    name: "Calça Plissada Camel",
    category: "Calças",
    price: 1250,
    image: "/images/products/calca-plissada-camel.jpg",
    badge: "Novo",
  },
];

export const bestSellers = products.filter((product) => product.bestSeller);

export const newArrivals = products.filter((product) => !product.bestSeller);

export const collections: Collection[] = [
  {
    id: "verao",
    season: "Verão",
    name: "Coleção Verão",
    description: "Calções, bermudas e vestidos leves para os dias quentes",
    image: "/images/products/calcoes-comfy-rosa.jpg",
    pieces: 14,
  },
  {
    id: "inverno",
    season: "Inverno",
    name: "Coleção Inverno",
    description: "Conjuntos suede e peças quentes para os dias frescos",
    image: "/images/products/conjunto-suede-preto.jpg",
    pieces: 10,
  },
  {
    id: "primavera",
    season: "Primavera",
    name: "Coleção Primavera",
    description: "Estampas vivas e tons suaves de transição",
    image: "/images/products/vestido-longo-azul.jpg",
    pieces: 12,
  },
  {
    id: "festa",
    season: "Ocasiões Especiais",
    name: "Noites & Eventos",
    description: "Vestidos corset e longos para brilhar em qualquer festa",
    image: "/images/products/vestido-corset-rubi.jpg",
    pieces: 8,
  },
];

export const testimonials: Testimonial[] = [
  {
    quote:
      "Encomendei um conjunto pelo WhatsApp e chegou no dia seguinte, impecável. A qualidade das peças é mesmo de outro nível.",
    name: "Anaísa M.",
    city: "Maputo",
  },
  {
    quote:
      "O atendimento é super atencioso — ajudaram-me a escolher o vestido perfeito para o casamento da minha irmã. Recomendo de olhos fechados!",
    name: "Vânia T.",
    city: "Matola",
  },
  {
    quote:
      "Finalmente uma loja com peças elegantes e preços justos. Já fiz três encomendas e nunca me desiludiu.",
    name: "Sheila C.",
    city: "Beira",
  },
];
